[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "saxs_analysis"
version = "0.0.1"
description = "A package for simulation, fitting and machine learning analysis of Small-Angle X-ray Scattering (SAXS) data"
authors = [{name = "Andy Sode Anker", email = "ansoan@dtu.dk"}]
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}