"""
Parameter Ranges for SAXS ML Models

This module defines the parameter ranges used in Small Angle X-ray Scattering (SAXS) 
machine learning models. It contains a dictionary 'param_ranges' that specifies
the allowed ranges or distributions for various SAXS model parameters.

The parameters include physical properties such as scale, background, radii,
length, thickness, scattering length densities (SLD), and various distribution
characteristics for different geometric shapes and structures.

Each parameter is assigned either a random value within a specified range
or a choice from predefined options. The global ``param_ranges`` dict is the single
source of sampling bounds for simulation and many ML pipelines; keep keys aligned with
``formfactor_params`` in :mod:`~SAXS_analysis.utils.formfactors`.

Note: Ensure that 'random' and 'numpy' are imported at the beginning of this file.
"""

from SAXS_analysis.utils.size_distribution_models import size_distribution_models

param_ranges = {
    'scale': (0.01, 1),
    'background': (0, 0.001),
    'radius': (3, 50),
    'radius_pd': (0, 0.5),
    'radius_pd_n': (35, 35),
    'radius_pd_nsigma': (3, 3),
    'radius_pd_type': size_distribution_models,
    'radius_minor': (3, 50),
    #'radius_minor_pd': (0, 0.5),
    'radius_minor_pd_n': (35, 35),
    'radius_minor_pd_nsigma': (3, 3),
    'radius_minor_pd_type': size_distribution_models,
    'axis_ratio': (1, 4),
    'x_core': (1, 4),
    'thick_shell': (3, 50),
    'x_polar_shell': (1, 2),
    'radius_lg': (3, 50),
    'radius_sm': (3, 50),
    'length': (3, 50),
    'length_pd': (0, 0.5),
    'length_pd_n': (35, 35),
    'length_pd_nsigma': (3, 3),
    'length_pd_type': size_distribution_models,
    #'length_a_pd': (0, 0.5),
    'length_a_pd_n': (35, 35),
    'length_a_pd_nsigma': (3, 3),
    'length_a_pd_type': size_distribution_models,
    'radius_polar': (3, 50),
    #'radius_polar_pd': (0, 0.5),
    'radius_polar_pd_n': (35, 35),
    'radius_polar_pd_nsigma': (3, 3),
    'radius_polar_pd_type': size_distribution_models,
    'radius_equatorial': (3, 50),
    #'radius_equatorial_pd': (0, 0.5),
    'radius_equatorial_pd_n': (35, 35),
    'radius_equatorial_pd_nsigma': (3, 3),
    'radius_equatorial_pd_type': size_distribution_models,
    'radius_equat_core': (3, 50),
    #'radius_equat_core_pd': (0, 0.5),
    'radius_equat_core_pd_n': (35, 35),
    'radius_equat_core_pd_nsigma': (3, 3),
    'radius_equat_core_pd_type': size_distribution_models,
    'radius_equat_minor': (3, 50),
    #'radius_equat_minor_pd': (0, 0.5),
    'radius_equat_minor_pd_n': (35, 35),
    'radius_equat_minor_pd_nsigma': (3, 3),
    'radius_equat_minor_pd_type': size_distribution_models,
    'radius_equat_major': (3, 50),
    #'radius_equat_major_pd': (0, 0.5),
    'radius_equat_major_pd_n': (35, 35),
    'radius_equat_major_pd_nsigma': (3, 3),
    'radius_equat_major_pd_type': size_distribution_models,
    'thickness': (0, 5),
    #'thickness_pd': (0, 0.5),
    'thickness_pd_n': (35, 35),
    'thickness_pd_nsigma': (3, 3),
    'thickness_pd_type': size_distribution_models,
    'sld': (1, 1),
    'sld_solvent': (0, 0),
    'sld_core': (0, 1),
    'sld_shell': (0, 1),
    'thick_core': (1, 25),
    'thick_layer': (1, 25),
    'n_stacking': (1, 10),
    'edge_sep': (1, 100),
    'num_peals': (1, 10),
    'length_a': (1, 100),
    'exponent_p': (1, 10),
    'fuzziness': (0.5, 10),
    'kuhn_length': (3, 50),
    #'kuhn_length_pd': (0, 0.5),
    'kuhn_length_pd_n': (35, 35),
    'kuhn_length_pd_nsigma': (3, 3),
    'kuhn_length_pd_type': size_distribution_models,
    'theta': (60, 60),
    'theta_pd': (0, 0.2),
    'theta_pd_n': (35, 35),
    'theta_pd_nsigma': (3, 3),
    'theta_pd_type': size_distribution_models,
    'phi': (60, 60),
    'phi_pd': (0, 0.2),
    'phi_pd_n': (35, 35),
    'phi_pd_nsigma': (3, 3),
    'phi_pd_type': size_distribution_models,
    'up_phi': (60, 60),
    'up_frac_i': (0.0, 0.0),
    'up_frac_f': (0.0, 0.0),
    'up_angle': (0.0, 0.0),
    'sld_M0': (0.0, 0.0),
    'sld_mtheta': (0.0, 0.0),
    'sld_mphi': (0.0, 0.0),
    'sld_solvent_M0': (0.0, 0.0),
    'sld_solvent_mtheta': (0.0, 0.0),
    'sld_solvent_mphi': (0.0, 0.0),
    'radius_effective': (3, 50),
    'volfraction': (0, 1),
    'volfraction_lg': (0, 1),
    'volfraction_sm': (0, 1),
    'power': (0, 4),
}