# Experiment identification
experiment_id: '00001'
experiment_name: 'classification_test'

# Data settings
data:
  file_name: "data/simulated/SAXS_dataset_100000_floatfloat16_structureFactor0.0percent_powerlaw0.0percent_qmin0.001_qmax1.5_numPoints1000_resolutionMin0.0_resolutionMax0.0_normalisationNone_noiseFalse.h5"
  num_data_points: 100000
  normalise_data: false

# Model settings
model:
  hyperparameter_optimisation: false
  use_gpu: true
  early_stopping_rounds: 25
  model_save_path: "models/classification/XGBoost_model_{num_data_points}_normData{normalise_data}_earlyStopping{early_stopping_rounds}_hyperparameter{hyperparameter_optimisation}.model"
  class_names_save_path: "models/classification/class_names_{num_data_points}_normData{normalise_data}_earlyStopping{early_stopping_rounds}_hyperparameter{hyperparameter_optimisation}.npy"

# Evaluation settings
evaluation:
  plot_results: false
  plot_confusion_matrix: false

# Verbosity level
verbose: 2
