# Experiment identification
experiment_id: '00001'  # Unique identifier for this experiment
experiment_name: 'regression_test'  # Descriptive name for the experiment

data:
  file_name: "data/simulated/SAXS_dataset_100000.h5"
  num_data_points: 100000
  normalise_data: false
  plot_data: false
  formfactor: 'sphere'

model:
  use_bayesian_optimization: false
  use_gpu: true
  model_save_path: "XGBoost_model_{num_data_points}.json"
  class_names_save_path: "XGBoost_models_ensemble/class_names.npy"

evaluation:
  plot_results: false
  plot_confusion_matrix: false

# Verbosity level
verbose: 2
